package unipotsdam.gf.modules.performance;

public enum PerformanceCandidates {
    DELETE_USER,
    CREATE_USER, LOGIN_USER, MODIFY_CHAT_ROOM, MODIFY_CHAT_ROOM_REQUEST, CREATE_ROOM, REGISTER_USER, ADD_TO_ROOM, ROCKET_LOGIN, STUDENT_ENTERS_PROJECT
}
