package unipotsdam.gf.process.tasks;

public enum TaskName {
    // Teacher Tasks
    WAIT_FOR_PARTICPANTS, CLOSE_GROUP_FINDING_PHASE, WAITING_FOR_GROUP,
    CLOSE_DOSSIER_FEEDBACK_PHASE,WAIT_FOR_REFLECTION,

    // Student Tasks
    UPLOAD_DOSSIER, GIVE_FEEDBACK, CREATE_QUIZ, WRITE_EJOURNAL, ANNOTATE_DOSSIER, FINALIZE_DOSSIER,
    FINALIZE_EJOURNAL,
    FORM_GROUPS_MANUALLY, EDIT_FORMED_GROUPS, CONTACT_GROUP_MEMBERS, ASSESSMENT, WAITING_FOR_STUDENT_DOSSIERS, EDIT_FEEDBACK
}
